# Project language
language: php

# Start mariadb service
services:
- mariadb

# Cache composer packages so "composer install" is faster
cache:
  directories:
  - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
  - php: 5.5
  - php: 5.6
  - php: 7.0
  - php: hhvm
  allow_failures:
  - php: hhvm


# Install composer dependencies,
# Create database, schema and fixtures
install:
- composer self-update
- composer install
- cp app/config/parameters.yml.dist app/config/parameters.yml
- php bin/console doctrine:database:create --env=test
- php bin/console doctrine:schema:create --env=test

before_script:
- wget https://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -O php-cs-fixer
- chmod a+x php-cs-fixer
- composer install
- composer require sensiolabs/security-checker

# Run script
script:
- "./php-cs-fixer fix src --rules=@Symfony --diff --dry-run -vvv"
- php bin/console lint:yaml config
- php bin/console security:check

# After a build, send email notification with the build results
notifications:
  email:
    recipients:
    - Jbagostin@gmail.com
    on_success: never
